name: CMake Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release, Debug]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libglfw3-dev libglm-dev libglew-dev

      - name: Install vcpkg on Windows
        if: matrix.os == 'windows-latest'
        run: |
          choco install git
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat

      - name: Install dependencies with vcpkg on Windows
        if: matrix.os == 'windows-latest'
        run: .\vcpkg\vcpkg.exe install glfw3 glm

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1.10

      - name: Set up Visual Studio
        if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Configure CMake on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Configure CMake on Windows
        if: matrix.os == 'windows-latest'
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }}

      - name: Archive build
        uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-build-${{ matrix.build_type }}
          path: build
